/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Mesa;
import Modelo.Mesero;
import Modelo.Pedido;
import Persistencia.MesaData;
import Persistencia.MeseroData;
import Persistencia.PedidoData;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tomic
 */
public class AltaPedido extends javax.swing.JInternalFrame {

    //VARIABLES:
    private MeseroData meseroD = new MeseroData();
    private Mesero meseroActual = null;
    private MesaData mesaD = new MesaData();
    private Mesa mesaActual = null;
    private boolean advertido = false; //para modificar
    private PedidoData pedidoD = new PedidoData();
    private Pedido pedidoNuevo = null;

    List<Mesero> listaMeseros;
    List<Mesa> listaMesa;

    public AltaPedido() {
        initComponents();
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCBmesas = new javax.swing.JComboBox<>();
        jCBmeseros = new javax.swing.JComboBox<>();
        jBguardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ALTA NUEVOS PEDIDOS");

        jCBmesas.setBackground(new java.awt.Color(255, 255, 255));
        jCBmesas.setForeground(new java.awt.Color(0, 0, 0));
        jCBmesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmesasActionPerformed(evt);
            }
        });

        jCBmeseros.setBackground(new java.awt.Color(255, 255, 255));
        jCBmeseros.setForeground(new java.awt.Color(0, 0, 0));
        jCBmeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmeserosActionPerformed(evt);
            }
        });

        jBguardar.setText("Alta Nuevo Pedido");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mesa:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mesero:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBmesas, 0, 196, Short.MAX_VALUE)
                            .addComponent(jCBmeseros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBmesas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBmeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addComponent(jBguardar)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBmesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmesasActionPerformed
        // "selected" COMBO BOX MESEROS responde al click
        meseroActual = (Mesero) jCBmeseros.getSelectedItem();
//        jBmodificar.setEnabled(true);
//        jBbaja.setEnabled(true);
        int idMesero = 0;

        try {
            if (meseroActual != null) {

                idMesero = meseroActual.getIdMesero();
//                //para comentar luego...
//                JOptionPane.showMessageDialog(null, "idMesero= "+idMesero);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error: " + e.toString());
        }
    }//GEN-LAST:event_jCBmesasActionPerformed

    private void jCBmeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmeserosActionPerformed
        // "selected" COMBO BOX MESAS responde al click
        mesaActual = (Mesa) jCBmesas.getSelectedItem();
//        jBmodificar.setEnabled(true);
//        jBbaja.setEnabled(true);
        int idMesa = 0;

        try {
            if (mesaActual != null) {

                idMesa = mesaActual.getIdMesa();
//                //para comentar luego...
//                JOptionPane.showMessageDialog(null, "idMesa= "+idMesa);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error: " + e.toString());
        }

    }//GEN-LAST:event_jCBmeserosActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // BOTON ALTA NUEVO PEDIDO

        pedidoNuevo = new Pedido(mesaActual, meseroActual);

        pedidoD.guardarPedido(pedidoNuevo);

        refrescarVentana();

    }//GEN-LAST:event_jBguardarActionPerformed

    private void llenarComboBoxMesas() {
        jCBmesas.removeAllItems(); // Limpia cualquier elemento previo en el combo box

        listaMesa = mesaD.listarMesas();

        for (Mesa item : listaMesa) {

            jCBmesas.addItem(item);

        }

        jCBmesas.setSelectedItem(null);
    }

    private void llenarComboBoxMeseros() {
        jCBmeseros.removeAllItems();
        listaMeseros = meseroD.listarMeseros();//LISTAR MESEROS SOLO TRAE LOS QUE NO ESTÁN DE BAJA LOGICA. vienen  los baja=0
        for (Mesero item : listaMeseros) {
            //jCBmeseros.addItem(item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase());
            jCBmeseros.addItem(item);

        }
        jCBmeseros.setSelectedItem(null);
    }

    private void refrescarVentana() {
        llenarComboBoxMesas();
        llenarComboBoxMeseros();
        //        limpiarCamposTexto();
        //        jBmodificar.setEnabled(false);
        //        jBbaja.setEnabled(false);
        //       
        //        jTFdni.setEditable(false); 
        //        jTFapellido.setEditable(false); 
        //        jTFnombre.setEditable(false); 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox<Mesa> jCBmesas;
    private javax.swing.JComboBox<Mesero> jCBmeseros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
