/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.*;
import Persistencia.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomic
 */
public class AtenderPedido extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    private ProductoData prodD = new ProductoData();
    private Producto productoNuevo = new Producto();
    private PedidoData pediD = new PedidoData();
    private Pedido pedidoNuevo = null;
    private DetalleData detalleD = new DetalleData();
    private Detalle detalleNuevo = null;
    List<Producto> listaProductos;
    List<Pedido> listaPedidos;
    
    public AtenderPedido() {
        initComponents();
        refrescarVentana();
        this.model = (DefaultTableModel) JTcarrito.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JCBproductos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        JBagregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JTFcantidad = new javax.swing.JTextField();
        JCBpedido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JBcobrar = new javax.swing.JButton();
        JLtotal = new javax.swing.JLabel();
        JTFtotalDetallesDe1pedido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTcarrito = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JCBproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBproductosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("PRODUCTO:");

        JBagregar.setBackground(new java.awt.Color(0, 153, 51));
        JBagregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBagregar.setText("AGREGAR AL PEDIDO");
        JBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("CANTIDAD:");

        JTFcantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JCBpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBpedidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("PEDIDO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(JBagregar)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(JTFcantidad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JCBpedido, 0, 355, Short.MAX_VALUE)
                            .addComponent(JCBproductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(JBagregar)
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JBcobrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBcobrar.setText("COBRAR PEDIDO");
        JBcobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcobrarActionPerformed(evt);
            }
        });

        JLtotal.setText("TOTAL $");

        JTFtotalDetallesDe1pedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTFtotalDetallesDe1pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtotalDetallesDe1pedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addComponent(JBcobrar)
                .addContainerGap(458, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLtotal)
                .addGap(63, 63, 63)
                .addComponent(JTFtotalDetallesDe1pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLtotal)
                    .addComponent(JTFtotalDetallesDe1pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBcobrar)
                .addGap(31, 31, 31))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        JTcarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUCTO", "DESCRIPCION", "CANTIDAD", "IMPORTE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTcarrito);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void llenarJCB() {//los dos JCB
        JCBproductos.removeAllItems();
        listaProductos = prodD.listarProductos();//Productos que no esten dados de baja
        JCBpedido.removeAllItems();
        listaPedidos = pediD.listarPedidos() ;
        for (Producto pro : listaProductos) {
            JCBproductos.addItem(pro);

        }
        for (Pedido pedi : listaPedidos){
            if(!pedi.isCobrada()){
                JCBpedido.addItem(pedi);//SE CARGAN PEDIDOS, SOLO LOS COBRADOS FALSE
            }
            
        }
    }
    
    private void refrescarVentana(){
        llenarJCB();
        
    }
    
    private boolean VerificaCampos(){
        try {
            String texto = JTFcantidad.getText().trim();
            int valor = Integer.parseInt(texto);

            if (valor > 0) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "LA CANTIDAD DEBE SER UN NUMERO POSITIVO");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "LA CANTIDAD DEBE SER UN NUMERO");
            return false;
        }
    }
    
    private void cargarProductos() {
            
            int cantidad = (Integer) Integer.parseInt(JTFcantidad.getText());
            Producto prodActual = (Producto) JCBproductos.getSelectedItem();
            double importe = cantidad * prodActual.getPrecio();

            Object[] fila = new Object[]{
                prodActual.getNombreProducto(),
                prodActual.getDescripcion(),
                cantidad,
                importe
            };
            model.addRow(fila);
    }  
    
    private void JCBproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBproductosActionPerformed
        
    }//GEN-LAST:event_JCBproductosActionPerformed

    private void JBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagregarActionPerformed
         //hacer nueva linea en la table detalle
        
        //producto
        Producto prodActual = (Producto) JCBproductos.getSelectedItem();
        //int cantidadProductos
        int cantidad = (Integer) Integer.parseInt(JTFcantidad.getText());
        //pedido JCBpedido
        Pedido pedidoActual = (Pedido) JCBpedido.getSelectedItem();
        //usamos constructor: public Detalle(Producto producto, int cantidadProductos, Pedido pedido)
        detalleNuevo= new Detalle(prodActual,cantidad,pedidoActual);
        detalleD.agregarProductosAunPedido(detalleNuevo);//guarda un detalle
        //prodActual,cantidad hay q modificar el stock
        for (int i = 0; i < cantidad; i++) {
            prodD.modifStockProducto(prodActual.getIdProducto());
        }
        imprimirTotalDeLosDetallesDelPedidoX();//esto tiene que imprimirse en la vista
        //imprime DETALLE en carrito a través de método CargarProductos 
        if (VerificaCampos() == true) {
            cargarProductos();
            JTFcantidad.setText("");
        }
    }//GEN-LAST:event_JBagregarActionPerformed

    private void JCBpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBpedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBpedidoActionPerformed

    private void JBcobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcobrarActionPerformed
        // USAR METODO COBRAR PEDIDO
        //USANDO LINEA 198 DE PEDIDDATA
        //public void cobrarPedido(Pedido pedido){      //recibo pedido existente
        //EL PEDIDO EXISTENTE QUE SE MANDA X PARAMETRO ES EL Q CB SELECTED ITEM
        
    }//GEN-LAST:event_JBcobrarActionPerformed

    private void imprimirTotalDeLosDetallesDelPedidoX(){
         // acá imprimir todo el tiempo el total del pedido
        //recorriendo todos los detalles de un medido
        //hace un total
        //usando linea 245 de DealleData
        //public Double sumarSubtotalesDeUnPedido(int idPedido){      //recibo ID de un pedido existente
        //pedido JCBpedido
        Pedido pedidoActual = (Pedido) JCBpedido.getSelectedItem();
        int idPedido= pedidoActual.getIdPedido();
        detalleD.sumarSubtotalesDeUnPedido(idPedido);
        //asi lo muestro pero falta poner en la vista
        JOptionPane.showMessageDialog(null,"el total a pagar en el pedido " + idPedido + "+ es de $: " +
                  detalleD.sumarSubtotalesDeUnPedido(idPedido));
    }
    private void JTFtotalDetallesDe1pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtotalDetallesDe1pedidoActionPerformed
       
        
    }//GEN-LAST:event_JTFtotalDetallesDe1pedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagregar;
    private javax.swing.JButton JBcobrar;
    private javax.swing.JComboBox<Pedido> JCBpedido;
    private javax.swing.JComboBox<Producto> JCBproductos;
    private javax.swing.JLabel JLtotal;
    private javax.swing.JTextField JTFcantidad;
    private javax.swing.JTextField JTFtotalDetallesDe1pedido;
    private javax.swing.JTable JTcarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
