/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Joaco
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);//posicion relativa ventana menu
        this.setSize(810, 608);//tamaño ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        ImageIcon icono=new ImageIcon(getClass().getResource("/Recursos/imagenesVistas/mesitasRestaurante.jpg"));
        Image miImagen=icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);}};
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMesas = new javax.swing.JMenu();
        jmiMesas = new javax.swing.JMenuItem();
        jmMeseros = new javax.swing.JMenu();
        jMenuItemMeseroMB = new javax.swing.JMenuItem();
        jMenuItemMeseroA = new javax.swing.JMenuItem();
        jMenuItemTABLAmesero = new javax.swing.JMenuItem();
        jmProductos = new javax.swing.JMenu();
        jmiProductos = new javax.swing.JMenuItem();
        jmiAltaProducto = new javax.swing.JMenuItem();
        jmiSTOCK = new javax.swing.JMenuItem();
        jmiListarProductos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiNuevoPedido = new javax.swing.JMenuItem();
        jmiAtenderPedido = new javax.swing.JMenuItem();
        jmiCobrarPedido = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante");

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        jmMesas.setText("MESAS");

        jmiMesas.setText("Mesas Disponibles");
        jmiMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMesasActionPerformed(evt);
            }
        });
        jmMesas.add(jmiMesas);

        jMenuBar1.add(jmMesas);

        jmMeseros.setText("MESEROS");

        jMenuItemMeseroMB.setText("MODIFICACION_ó_BAJA");
        jMenuItemMeseroMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMeseroMBActionPerformed(evt);
            }
        });
        jmMeseros.add(jMenuItemMeseroMB);

        jMenuItemMeseroA.setText("Alta Nuevo Mesero");
        jMenuItemMeseroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMeseroAActionPerformed(evt);
            }
        });
        jmMeseros.add(jMenuItemMeseroA);

        jMenuItemTABLAmesero.setText("LISTAR TODOS LOS MESEROS");
        jMenuItemTABLAmesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTABLAmeseroActionPerformed(evt);
            }
        });
        jmMeseros.add(jMenuItemTABLAmesero);

        jMenuBar1.add(jmMeseros);

        jmProductos.setText("PRODUCTOS");

        jmiProductos.setText("CONSULTA Productos");
        jmiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosActionPerformed(evt);
            }
        });
        jmProductos.add(jmiProductos);

        jmiAltaProducto.setText("ALTA nuevo PRODUCTO");
        jmiAltaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAltaProductoActionPerformed(evt);
            }
        });
        jmProductos.add(jmiAltaProducto);

        jmiSTOCK.setText("Stock");
        jmiSTOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSTOCKActionPerformed(evt);
            }
        });
        jmProductos.add(jmiSTOCK);

        jmiListarProductos.setText("Listar PRODUCTOS");
        jmProductos.add(jmiListarProductos);

        jMenuBar1.add(jmProductos);

        jMenu1.setText("PEDIDOS");

        jmiNuevoPedido.setText("NUEVO PEDIDO");
        jmiNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiNuevoPedido);

        jmiAtenderPedido.setText("ATENDER PEDIDO");
        jMenu1.add(jmiAtenderPedido);

        jmiCobrarPedido.setText("COBRAR PEDIDO");
        jMenu1.add(jmiCobrarPedido);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMesasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaMesas mesas = new VistaMesas();
        mesas.setVisible(true);
        escritorio.add(mesas);
    }//GEN-LAST:event_jmiMesasActionPerformed

    private void jMenuItemMeseroMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeseroMBActionPerformed
       // MESERO MODIFICACION Y BAJA
        escritorio.removeAll();
        escritorio.repaint();
        GestionMesero meseroG = new GestionMesero();
        meseroG.setVisible(true);
        escritorio.add(meseroG);
    }//GEN-LAST:event_jMenuItemMeseroMBActionPerformed

    private void jMenuItemMeseroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeseroAActionPerformed
        // MESERO ALTA NUEVO MESERO
        escritorio.removeAll();
        escritorio.repaint();
        AltaMesero meseroAlta = new AltaMesero();
        meseroAlta.setVisible(true);
        escritorio.add(meseroAlta);
    }//GEN-LAST:event_jMenuItemMeseroAActionPerformed

    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaProducto vistaProducto = new VistaProducto();
        vistaProducto.setVisible(true);
        escritorio.add(vistaProducto);
    }//GEN-LAST:event_jmiProductosActionPerformed

    private void jMenuItemTABLAmeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTABLAmeseroActionPerformed
        // MESEROStodos imprimir en tabla
        escritorio.removeAll();
        escritorio.repaint();
        VistaMesero meseroV = new VistaMesero();
        meseroV.setVisible(true);
        escritorio.add(meseroV);
    }//GEN-LAST:event_jMenuItemTABLAmeseroActionPerformed

    private void jmiSTOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSTOCKActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        StockVistas  SV = new StockVistas();
        SV.setVisible(true);
        escritorio.add(SV); 
    }//GEN-LAST:event_jmiSTOCKActionPerformed

    private void jmiAltaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaProductoActionPerformed
        //ALTA DE PRODUCTOS
        escritorio.removeAll();
        escritorio.repaint();
        AgregarProducto AP = new AgregarProducto();
        AP.setVisible(true);
        escritorio.add(AP);
    }//GEN-LAST:event_jmiAltaProductoActionPerformed

    private void jmiNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoPedidoActionPerformed
// NUEVO PEDIDO ALTA PEDIDO
        escritorio.removeAll();
        escritorio.repaint();
        NuevoPedido pedidoN = new NuevoPedido();
        pedidoN.setVisible(true);
        escritorio.add(pedidoN);        // TODO add your handling code here:
    }//GEN-LAST:event_jmiNuevoPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemMeseroA;
    private javax.swing.JMenuItem jMenuItemMeseroMB;
    private javax.swing.JMenuItem jMenuItemTABLAmesero;
    private javax.swing.JMenu jmMesas;
    private javax.swing.JMenu jmMeseros;
    private javax.swing.JMenu jmProductos;
    private javax.swing.JMenuItem jmiAltaProducto;
    private javax.swing.JMenuItem jmiAtenderPedido;
    private javax.swing.JMenuItem jmiCobrarPedido;
    private javax.swing.JMenuItem jmiListarProductos;
    private javax.swing.JMenuItem jmiMesas;
    private javax.swing.JMenuItem jmiNuevoPedido;
    private javax.swing.JMenuItem jmiProductos;
    private javax.swing.JMenuItem jmiSTOCK;
    // End of variables declaration//GEN-END:variables
}
