/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Joaco
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);//posicion relativa ventana menu
        this.setSize(810, 608);//tamaño ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono=new ImageIcon(getClass().getResource("/Recursos/imagenesVistas/mesitasRestaurante.jpg"));
        Image miImagen=icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);}};
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiMesas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemMeseroMB = new javax.swing.JMenuItem();
        jMenuItemMeseroA = new javax.swing.JMenuItem();
<<<<<<< Updated upstream
        jmiProductos = new javax.swing.JMenu();
=======
        jMenuItemTABLAmesero = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
>>>>>>> Stashed changes
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante");

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        jMenu1.setText("MESAS");

        jmiMesas.setText("Mesas Disponibles");
        jmiMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMesasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiMesas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("MESEROS");

        jMenuItemMeseroMB.setText("MODIFICACION_ó_BAJA");
        jMenuItemMeseroMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMeseroMBActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMeseroMB);

        jMenuItemMeseroA.setText("Alta Nuevo Mesero");
        jMenuItemMeseroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMeseroAActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMeseroA);

        jMenuItemTABLAmesero.setText("LISTAR TODOS LOS MESEROS");
        jMenuItemTABLAmesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTABLAmeseroActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTABLAmesero);

        jMenuBar1.add(jMenu2);

        jmiProductos.setText("PRODUCTOS");
        jmiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Gestion Productos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmiProductos.add(jMenuItem2);

        jMenuBar1.add(jmiProductos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMesasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaMesas mesas = new VistaMesas();
        mesas.setVisible(true);
        escritorio.add(mesas);
    }//GEN-LAST:event_jmiMesasActionPerformed

    private void jMenuItemMeseroMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeseroMBActionPerformed
       // MESERO MODIFICACION Y BAJA
        escritorio.removeAll();
        escritorio.repaint();
        GestionMesero meseroG = new GestionMesero();
        meseroG.setVisible(true);
        escritorio.add(meseroG);
    }//GEN-LAST:event_jMenuItemMeseroMBActionPerformed

    private void jMenuItemMeseroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeseroAActionPerformed
        // MESERO ALTA NUEVO MESERO
        escritorio.removeAll();
        escritorio.repaint();
        AltaMesero meseroAlta = new AltaMesero();
        meseroAlta.setVisible(true);
        escritorio.add(meseroAlta);
    }//GEN-LAST:event_jMenuItemMeseroAActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

<<<<<<< Updated upstream
    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
      // MESERO ALTA NUEVO MESERO
        escritorio.removeAll();
        escritorio.repaint();
        VistaProducto productos = new VistaProducto();
        productos.setVisible(true);
        escritorio.add(productos);
    }//GEN-LAST:event_jmiProductosActionPerformed
=======
    private void jMenuItemTABLAmeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTABLAmeseroActionPerformed
        // MESEROStodos imprimir en tabla
        escritorio.removeAll();
        escritorio.repaint();
        VistaMesero meseroV = new VistaMesero();
        meseroV.setVisible(true);
        escritorio.add(meseroV);
    }//GEN-LAST:event_jMenuItemTABLAmeseroActionPerformed
>>>>>>> Stashed changes

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemMeseroA;
    private javax.swing.JMenuItem jMenuItemMeseroMB;
    private javax.swing.JMenuItem jMenuItemTABLAmesero;
    private javax.swing.JMenuItem jmiMesas;
    private javax.swing.JMenu jmiProductos;
    // End of variables declaration//GEN-END:variables
}
