/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.Mesa;
import Modelo.Mesero;
import Modelo.Pedido;
import Persistencia.MesaData;
import Persistencia.MeseroData;
import Persistencia.PedidoData;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mgts
 */
public class NuevoPedido extends javax.swing.JFrame {

    //VARIABLES:
    private MeseroData meseroD=new MeseroData();
    private Mesero meseroActual=null;
    private MesaData mesaD=new MesaData();
    private Mesa mesaActual=null;
    private boolean advertido= false; //para modificar
     private PedidoData pedidoD=new PedidoData();
    private Pedido pedidoNuevo=null;
    
    List<Mesero> listaMeseros; 
    List<Mesa> listaMesa; 
    public NuevoPedido() {
        initComponents();
        
         refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNuevoPedido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBmeseros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jCBmesas = new javax.swing.JComboBox<>();
        jBalta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlNuevoPedido.setBackground(new java.awt.Color(255, 255, 255));
        jlNuevoPedido.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jlNuevoPedido.setText("NUEVO PEDIDO");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Mesero:");

        jCBmeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmeserosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Mesa: ");

        jCBmesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmesasActionPerformed(evt);
            }
        });

        jBalta.setBackground(new java.awt.Color(51, 102, 255));
        jBalta.setText("ALTA NUEVO PEDIDO");
        jBalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jlNuevoPedido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBmesas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBmeseros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBalta, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlNuevoPedido)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addComponent(jCBmesas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCBmeseros, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jBalta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBmeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmeserosActionPerformed
        // "selected" COMBO BOX MESEROS responde al click
        meseroActual= (Mesero) jCBmeseros.getSelectedItem();
//        jBmodificar.setEnabled(true);
//        jBbaja.setEnabled(true);
        int idMesero=0;
        
        try{
            if (meseroActual !=null){
                
                idMesero=meseroActual.getIdMesero();
//                //para comentar luego...
//                JOptionPane.showMessageDialog(null, "idMesero= "+idMesero);
               
            } }catch(Exception e){
                JOptionPane.showMessageDialog(null, "error: "+e.toString());
            }
    }//GEN-LAST:event_jCBmeserosActionPerformed

    private void jCBmesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmesasActionPerformed
        // "selected" COMBO BOX MESAS responde al click
        mesaActual= (Mesa) jCBmesas.getSelectedItem();
//        jBmodificar.setEnabled(true);
//        jBbaja.setEnabled(true);
        int idMesa=0;
        
        try{
            if (mesaActual !=null){
                
                idMesa=mesaActual.getIdMesa();
//                //para comentar luego...
//                JOptionPane.showMessageDialog(null, "idMesa= "+idMesa);
               
            } }catch(Exception e){
                JOptionPane.showMessageDialog(null, "error: "+e.toString());
            }

    }//GEN-LAST:event_jCBmesasActionPerformed

    private void jBaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaltaActionPerformed
        // BOTON ALTA NUEVO PEDIDO

      

        pedidoNuevo= new Pedido(mesaActual,meseroActual);

        pedidoD.guardarPedido(pedidoNuevo); 
        

        refrescarVentana();

    }//GEN-LAST:event_jBaltaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalta;
    private javax.swing.JComboBox<Mesa> jCBmesas;
    private javax.swing.JComboBox<Mesero> jCBmeseros;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlNuevoPedido;
    // End of variables declaration//GEN-END:variables

    private void llenarComboBoxMesas() {
    jCBmesas.removeAllItems(); // Limpia cualquier elemento previo en el combo box
    
    listaMesa = mesaD.listarMesas();
    
        for (Mesa item : listaMesa) {
            
            jCBmesas.addItem(item);
            
        }
        
    jCBmesas.setSelectedItem(null);
}
    
    
    
    
    
    private void llenarComboBoxMeseros(){
        jCBmeseros.removeAllItems();
        listaMeseros= meseroD.listarMeseros();//LISTAR MESEROS SOLO TRAE LOS QUE NO ESTÁN DE BAJA LOGICA. vienen  los baja=0
                for (Mesero item : listaMeseros) {
            //jCBmeseros.addItem(item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase());
            jCBmeseros.addItem(item);
            
        }
            jCBmeseros.setSelectedItem(null);
    }

 
    

 private void refrescarVentana(){
        llenarComboBoxMesas();
        llenarComboBoxMeseros();
//        limpiarCamposTexto();
//        jBmodificar.setEnabled(false);
//        jBbaja.setEnabled(false);
//       
//        jTFdni.setEditable(false); 
//        jTFapellido.setEditable(false); 
//        jTFnombre.setEditable(false); 
    }
}
