/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Producto;
import Persistencia.ProductoData;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tomic
 */
public class StockVistas extends javax.swing.JInternalFrame {
    
    private ProductoData prodD=new ProductoData();
    
    List<Producto> listaProductos;
    /**
     * Creates new form StockVistas
     */
    public StockVistas() {

        initComponents();
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JCBproductos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        JBguardar = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JTFstock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFagregados = new javax.swing.JTextField();

        JCBproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBproductosActionPerformed(evt);
            }
        });

        jLabel1.setText("MANEJO DE STOCK");

        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Stock:");

        JTFstock.setEditable(false);

        jLabel3.setText("Productos Agregados:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBproductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(JBsalir)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFstock)
                            .addComponent(JTFagregados))))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(JCBproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFagregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBguardar)
                    .addComponent(JBsalir))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void llenarJCB() {
        JCBproductos.removeAllItems();
        listaProductos = prodD.listarProductos();//Productos que no esten dados de baja
        for (Producto pro : listaProductos) {
            JCBproductos.addItem(pro);

        }
    }
    
    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_JBsalirActionPerformed

    private void JCBproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBproductosActionPerformed
        Producto prodActual = (Producto) JCBproductos.getSelectedItem();
        JTFstock.setText("" + prodActual.getStock());
    }//GEN-LAST:event_JCBproductosActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        if (VerificaCampos() == true) {
            
            Producto prodActual = (Producto) JCBproductos.getSelectedItem();
            
            int stock = Integer.parseInt(JTFstock.getText());
            int agregados = Integer.parseInt(JTFagregados.getText());
            int nuevoStock = (stock + agregados);
          
            ProductoData pd = new ProductoData();
            prodActual.setStock(nuevoStock);
            pd.actualizarProducto(prodActual);
            //limpiar campos
            JTFstock.setText("");
            JTFagregados.setText("");
           
        }
    }//GEN-LAST:event_JBguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBsalir;
    private javax.swing.JComboBox<Producto> JCBproductos;
    private javax.swing.JTextField JTFagregados;
    private javax.swing.JTextField JTFstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana(){
        llenarJCB();
    }
    
    private boolean VerificaCampos() {

        //verificamos que se seleccione un producto primero 
        Producto prod = (Producto) JCBproductos.getSelectedItem();
        if (prod == null) {
            JOptionPane.showMessageDialog(null, "SELECCIONE UN PRODUCTO");
            return false;
        }

        //aca verificamos que el campo para agregar productos no este vacio
        String agregados = JTFagregados.getText().trim();
        if (agregados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "INGRESE UN NUMERO DE PRODUCTOS A AGREGAR");
            return false;
        }
        try {
            int stockval = Integer.parseInt(agregados);
            if (stockval == 0) {  // Verificar que el stock sea un numero restable o sumable
                JOptionPane.showMessageDialog(null, "EL STOCK AGREGADO NO PUEDE SER 0");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "NUMERO INVALIDO");
            return false;
        }
        
        return true;
    }
}


