/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Mesero;
import Modelo.Pedido;
import Persistencia.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VistaMesero extends javax.swing.JInternalFrame {

        private DefaultTableModel model; 
        List<Mesero> listaMeseros;
        private MeseroData meseroD=new MeseroData();
        private Mesero meseroActual=null;
        private PedidoData pedidoD=new PedidoData();
        private Pedido pedidoNuevo=null;
    
        List<Pedido> listaPedidos; 
 
    public VistaMesero() {
        initComponents();
        this.model= (DefaultTableModel) jtMeseros.getModel();
      
        this.listaMeseros= meseroD.listarMeseros();
        llenarComboBox();
        armarCabecera();
        //LIMPIAMOS TABLA
        model.setRowCount(0);
        //LLENAMOS TABLA
        for (Mesero item : listaMeseros) {
            model.addRow(new Object[]{
            item.getDni(),
            item.getApellido(),
            item.getNombre()});
            
        }

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBmeseros = new javax.swing.JComboBox<>();
        JBmpdiario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMeseros = new javax.swing.JTable();
        JBhistorialPedidos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText(" CONSULTA  MESEROS ");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Mesero:");

        jCBmeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmeserosActionPerformed(evt);
            }
        });

        JBmpdiario.setBackground(new java.awt.Color(102, 255, 204));
        JBmpdiario.setText("PEDIDOS X MESERO DIARIO");
        JBmpdiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmpdiarioActionPerformed(evt);
            }
        });

        jtMeseros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtMeseros.setFocusCycleRoot(true);
        jScrollPane2.setViewportView(jtMeseros);

        JBhistorialPedidos.setBackground(new java.awt.Color(102, 255, 204));
        JBhistorialPedidos.setText("HISTORIAL DE PEDIDOS ");
        JBhistorialPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBhistorialPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(JBhistorialPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(JBmpdiario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jCBmeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBmeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBhistorialPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBmpdiario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBmpdiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmpdiarioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        MPedidosDia hp = new MPedidosDia();
        hp.setVisible(true);
        escritorio.add(hp);
    }//GEN-LAST:event_JBmpdiarioActionPerformed

    private void jCBmeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmeserosActionPerformed
        // COMBO BOX MESEROS
                // "selected" COMBO BOX MESEROS responde al click
     meseroActual= (Mesero) jCBmeseros.getSelectedItem();
 
     try{
         if (meseroActual !=null){
             
 
         } }catch(Exception e){
        JOptionPane.showMessageDialog(null, "error: "+e.toString());
//    }
//        borrarFilas();
//        int idMeseroActual=-1;
         
//        String meseroSeleccionado= jCBmeseros.getSelectedItem().toString();
//        this.listaMeseros= meseroD.listarMeseros();
//        for (Mesero item : listaMeseros) {
//            String m= item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase();
//            if (m.equals(meseroSeleccionado)){
//                
//            }
//          //  jCBmeseros.addItem();
        }    
        
        
    }//GEN-LAST:event_jCBmeserosActionPerformed

    private void JBhistorialPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBhistorialPedidosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        HistorialPedidos hp = new HistorialPedidos();
        hp.setVisible(true);
        escritorio.add(hp);
    }//GEN-LAST:event_JBhistorialPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBhistorialPedidos;
    private javax.swing.JButton JBmpdiario;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JComboBox<Mesero> jCBmeseros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtMeseros;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera(){
        model.addColumn("DNI");
        model.addColumn("APELLIDO");
        model.addColumn("NOMBRE");
    }
    private void borrarFilas(){
        int filas=model.getRowCount()-1;
        for (int f = filas; f >=0; f--) {
            model.removeRow(f);
            
        }
    }
    
//    private void llenarComboBox(){
//                for (Mesero item : listaMeseros) {
//            jCBmeseros.addItem(item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase());
//            
//        }
//    }

     private void llenarComboBox(){
        jCBmeseros.removeAllItems();
        listaMeseros= meseroD.listarMeseros();//LISTAR MESEROS SOLO TRAE LOS QUE NO ESTÁN DE BAJA LOGICA. vienen  los baja=0
                for (Mesero item : listaMeseros) {
            //jCBmeseros.addItem(item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase());
            jCBmeseros.addItem(item);
            
        }
                jCBmeseros.setSelectedItem(null);
    }

}
