/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Mesero;
import Modelo.Pedido;
import Persistencia.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VistaMesero extends javax.swing.JInternalFrame {

        private DefaultTableModel model; 
        List<Mesero> listaMeseros;
        private MeseroData meseroD=new MeseroData();
        private Mesero meseroActual=null;
        private PedidoData pedidoD=new PedidoData();
        private Pedido pedidoNuevo=null;
    
        List<Pedido> listaPedidos; 
 
    public VistaMesero() {
        initComponents();
        this.model= (DefaultTableModel) jtMeseros.getModel();
      
        this.listaMeseros= meseroD.listarMeseros();
        llenarComboBox();
        armarCabecera();
        //LIMPIAMOS TABLA
        model.setRowCount(0);
        //LLENAMOS TABLA
        for (Mesero item : listaMeseros) {
            model.addRow(new Object[]{
            item.getDni(),
            item.getApellido(),
            item.getNombre()});
            
        }

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBmeseros = new javax.swing.JComboBox<>();
        jBhistorialPedidosXMesero = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMeseros = new javax.swing.JTable();
        jBhistorialPedidosXMesero1 = new javax.swing.JButton();
        jBhistorialPedidosXMesero2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText(" CONSULTA  MESEROS ");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Mesero:");

        jCBmeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmeserosActionPerformed(evt);
            }
        });

        jBhistorialPedidosXMesero.setBackground(new java.awt.Color(102, 255, 204));
        jBhistorialPedidosXMesero.setText("HISTORIAL DE PEDIDOS x Mesero");
        jBhistorialPedidosXMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhistorialPedidosXMeseroActionPerformed(evt);
            }
        });

        jtMeseros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtMeseros.setFocusCycleRoot(true);
        jScrollPane2.setViewportView(jtMeseros);

        jBhistorialPedidosXMesero1.setBackground(new java.awt.Color(102, 255, 204));
        jBhistorialPedidosXMesero1.setText("HISTORIAL DE PEDIDOS x Mesero");
        jBhistorialPedidosXMesero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhistorialPedidosXMesero1ActionPerformed(evt);
            }
        });

        jBhistorialPedidosXMesero2.setBackground(new java.awt.Color(102, 255, 204));
        jBhistorialPedidosXMesero2.setText("HISTORIAL DE PEDIDOS x Mesero");
        jBhistorialPedidosXMesero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhistorialPedidosXMesero2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBhistorialPedidosXMesero2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBhistorialPedidosXMesero1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBhistorialPedidosXMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel1)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBmeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBmeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBhistorialPedidosXMesero2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBhistorialPedidosXMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBhistorialPedidosXMesero1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBhistorialPedidosXMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhistorialPedidosXMeseroActionPerformed

        // AQUI CONSULTAREMOS CON TRONCAL PEDIDOS 
        
        meseroActual=(Mesero) jCBmeseros.getSelectedItem();
        
        try{
            if (meseroActual !=null){
                
                
        pedidoD.listarPedidosPorMesero(meseroActual.getIdMesero());
        
       } } 
            catch (Exception e){
                    JOptionPane.showMessageDialog(null, "error: "+e.toString());
                    }
        
        
    }//GEN-LAST:event_jBhistorialPedidosXMeseroActionPerformed

    private void jCBmeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmeserosActionPerformed
        // COMBO BOX MESEROS
                // "selected" COMBO BOX MESEROS responde al click
     meseroActual= (Mesero) jCBmeseros.getSelectedItem();
 
     try{
         if (meseroActual !=null){
             
 
         } }catch(Exception e){
        JOptionPane.showMessageDialog(null, "error: "+e.toString());
//    }
//        borrarFilas();
//        int idMeseroActual=-1;
         
//        String meseroSeleccionado= jCBmeseros.getSelectedItem().toString();
//        this.listaMeseros= meseroD.listarMeseros();
//        for (Mesero item : listaMeseros) {
//            String m= item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase();
//            if (m.equals(meseroSeleccionado)){
//                
//            }
//          //  jCBmeseros.addItem();
        }    
        
        
    }//GEN-LAST:event_jCBmeserosActionPerformed

    private void jBhistorialPedidosXMesero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhistorialPedidosXMesero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBhistorialPedidosXMesero1ActionPerformed

    private void jBhistorialPedidosXMesero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhistorialPedidosXMesero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBhistorialPedidosXMesero2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBhistorialPedidosXMesero;
    private javax.swing.JButton jBhistorialPedidosXMesero1;
    private javax.swing.JButton jBhistorialPedidosXMesero2;
    private javax.swing.JComboBox<Mesero> jCBmeseros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtMeseros;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera(){
        model.addColumn("DNI");
        model.addColumn("APELLIDO");
        model.addColumn("NOMBRE");
    }
    private void borrarFilas(){
        int filas=model.getRowCount()-1;
        for (int f = filas; f >=0; f--) {
            model.removeRow(f);
            
        }
    }
    
//    private void llenarComboBox(){
//                for (Mesero item : listaMeseros) {
//            jCBmeseros.addItem(item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase());
//            
//        }
//    }

     private void llenarComboBox(){
        jCBmeseros.removeAllItems();
        listaMeseros= meseroD.listarMeseros();//LISTAR MESEROS SOLO TRAE LOS QUE NO ESTÁN DE BAJA LOGICA. vienen  los baja=0
                for (Mesero item : listaMeseros) {
            //jCBmeseros.addItem(item.getDni()+", "+item.getApellido().toUpperCase()+", "+item.getNombre().toUpperCase());
            jCBmeseros.addItem(item);
            
        }
                jCBmeseros.setSelectedItem(null);
    }

}
